/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AgendasIndexRouteImport } from './routes/agendas.index'
import { Route as AuditoriaIndexRouteImport } from './routes/auditoria.index'
import { Route as ConsultaInventariosIndexRouteImport } from './routes/consulta-inventarios.index'
import { Route as ConsultaTransferenciasIndexRouteImport } from './routes/consulta-transferencias.index'
import { Route as EvaluacionesIndexRouteImport } from './routes/evaluaciones.index'
import { Route as EvaluacionesIdRouteImport } from './routes/evaluaciones.$id'
import { Route as EvaluacionesNuevaRouteImport } from './routes/evaluaciones.nueva'
import { Route as IntervencionesIndexRouteImport } from './routes/intervenciones.index'
import { Route as IntervencionesIdRouteImport } from './routes/intervenciones.$id'
import { Route as IntervencionesNuevaRouteImport } from './routes/intervenciones.nueva'
import { Route as InventarioIndexRouteImport } from './routes/inventario.index'
import { Route as SucursalesIndexRouteImport } from './routes/sucursales.index'
import { Route as TransferenciasIndexRouteImport } from './routes/transferencias.index'
import { Route as TransferenciasIdRouteImport } from './routes/transferencias.$id'
import { Route as TransferenciasNuevaRouteImport } from './routes/transferencias.nueva'
import { Route as ApiOrdsSplatRouteImport } from './routes/api/ords.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendasIndexRoute = AgendasIndexRouteImport.update({
  id: '/agendas/',
  path: '/agendas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaIndexRoute = AuditoriaIndexRouteImport.update({
  id: '/auditoria/',
  path: '/auditoria/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaInventariosIndexRoute =
  ConsultaInventariosIndexRouteImport.update({
    id: '/consulta-inventarios/',
    path: '/consulta-inventarios/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsultaTransferenciasIndexRoute =
  ConsultaTransferenciasIndexRouteImport.update({
    id: '/consulta-transferencias/',
    path: '/consulta-transferencias/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EvaluacionesIndexRoute = EvaluacionesIndexRouteImport.update({
  id: '/evaluaciones/',
  path: '/evaluaciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluacionesIdRoute = EvaluacionesIdRouteImport.update({
  id: '/evaluaciones/$id',
  path: '/evaluaciones/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluacionesNuevaRoute = EvaluacionesNuevaRouteImport.update({
  id: '/evaluaciones/nueva',
  path: '/evaluaciones/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const IntervencionesIndexRoute = IntervencionesIndexRouteImport.update({
  id: '/intervenciones/',
  path: '/intervenciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntervencionesIdRoute = IntervencionesIdRouteImport.update({
  id: '/intervenciones/$id',
  path: '/intervenciones/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IntervencionesNuevaRoute = IntervencionesNuevaRouteImport.update({
  id: '/intervenciones/nueva',
  path: '/intervenciones/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioIndexRoute = InventarioIndexRouteImport.update({
  id: '/inventario/',
  path: '/inventario/',
  getParentRoute: () => rootRouteImport,
} as any)
const SucursalesIndexRoute = SucursalesIndexRouteImport.update({
  id: '/sucursales/',
  path: '/sucursales/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferenciasIndexRoute = TransferenciasIndexRouteImport.update({
  id: '/transferencias/',
  path: '/transferencias/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferenciasIdRoute = TransferenciasIdRouteImport.update({
  id: '/transferencias/$id',
  path: '/transferencias/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferenciasNuevaRoute = TransferenciasNuevaRouteImport.update({
  id: '/transferencias/nueva',
  path: '/transferencias/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdsSplatRoute = ApiOrdsSplatRouteImport.update({
  id: '/api/ords/$',
  path: '/api/ords/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/home': typeof HomeRoute
  '/evaluaciones/$id': typeof EvaluacionesIdRoute
  '/evaluaciones/nueva': typeof EvaluacionesNuevaRoute
  '/intervenciones/$id': typeof IntervencionesIdRoute
  '/intervenciones/nueva': typeof IntervencionesNuevaRoute
  '/transferencias/$id': typeof TransferenciasIdRoute
  '/transferencias/nueva': typeof TransferenciasNuevaRoute
  '/agendas/': typeof AgendasIndexRoute
  '/auditoria/': typeof AuditoriaIndexRoute
  '/consulta-inventarios/': typeof ConsultaInventariosIndexRoute
  '/consulta-transferencias/': typeof ConsultaTransferenciasIndexRoute
  '/evaluaciones/': typeof EvaluacionesIndexRoute
  '/intervenciones/': typeof IntervencionesIndexRoute
  '/inventario/': typeof InventarioIndexRoute
  '/sucursales/': typeof SucursalesIndexRoute
  '/transferencias/': typeof TransferenciasIndexRoute
  '/api/ords/$': typeof ApiOrdsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/home': typeof HomeRoute
  '/evaluaciones/$id': typeof EvaluacionesIdRoute
  '/evaluaciones/nueva': typeof EvaluacionesNuevaRoute
  '/intervenciones/$id': typeof IntervencionesIdRoute
  '/intervenciones/nueva': typeof IntervencionesNuevaRoute
  '/transferencias/$id': typeof TransferenciasIdRoute
  '/transferencias/nueva': typeof TransferenciasNuevaRoute
  '/agendas': typeof AgendasIndexRoute
  '/auditoria': typeof AuditoriaIndexRoute
  '/consulta-inventarios': typeof ConsultaInventariosIndexRoute
  '/consulta-transferencias': typeof ConsultaTransferenciasIndexRoute
  '/evaluaciones': typeof EvaluacionesIndexRoute
  '/intervenciones': typeof IntervencionesIndexRoute
  '/inventario': typeof InventarioIndexRoute
  '/sucursales': typeof SucursalesIndexRoute
  '/transferencias': typeof TransferenciasIndexRoute
  '/api/ords/$': typeof ApiOrdsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/home': typeof HomeRoute
  '/evaluaciones/$id': typeof EvaluacionesIdRoute
  '/evaluaciones/nueva': typeof EvaluacionesNuevaRoute
  '/intervenciones/$id': typeof IntervencionesIdRoute
  '/intervenciones/nueva': typeof IntervencionesNuevaRoute
  '/transferencias/$id': typeof TransferenciasIdRoute
  '/transferencias/nueva': typeof TransferenciasNuevaRoute
  '/agendas/': typeof AgendasIndexRoute
  '/auditoria/': typeof AuditoriaIndexRoute
  '/consulta-inventarios/': typeof ConsultaInventariosIndexRoute
  '/consulta-transferencias/': typeof ConsultaTransferenciasIndexRoute
  '/evaluaciones/': typeof EvaluacionesIndexRoute
  '/intervenciones/': typeof IntervencionesIndexRoute
  '/inventario/': typeof InventarioIndexRoute
  '/sucursales/': typeof SucursalesIndexRoute
  '/transferencias/': typeof TransferenciasIndexRoute
  '/api/ords/$': typeof ApiOrdsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/home'
    | '/evaluaciones/$id'
    | '/evaluaciones/nueva'
    | '/intervenciones/$id'
    | '/intervenciones/nueva'
    | '/transferencias/$id'
    | '/transferencias/nueva'
    | '/agendas/'
    | '/auditoria/'
    | '/consulta-inventarios/'
    | '/consulta-transferencias/'
    | '/evaluaciones/'
    | '/intervenciones/'
    | '/inventario/'
    | '/sucursales/'
    | '/transferencias/'
    | '/api/ords/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/home'
    | '/evaluaciones/$id'
    | '/evaluaciones/nueva'
    | '/intervenciones/$id'
    | '/intervenciones/nueva'
    | '/transferencias/$id'
    | '/transferencias/nueva'
    | '/agendas'
    | '/auditoria'
    | '/consulta-inventarios'
    | '/consulta-transferencias'
    | '/evaluaciones'
    | '/intervenciones'
    | '/inventario'
    | '/sucursales'
    | '/transferencias'
    | '/api/ords/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/home'
    | '/evaluaciones/$id'
    | '/evaluaciones/nueva'
    | '/intervenciones/$id'
    | '/intervenciones/nueva'
    | '/transferencias/$id'
    | '/transferencias/nueva'
    | '/agendas/'
    | '/auditoria/'
    | '/consulta-inventarios/'
    | '/consulta-transferencias/'
    | '/evaluaciones/'
    | '/intervenciones/'
    | '/inventario/'
    | '/sucursales/'
    | '/transferencias/'
    | '/api/ords/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  HomeRoute: typeof HomeRoute
  EvaluacionesIdRoute: typeof EvaluacionesIdRoute
  EvaluacionesNuevaRoute: typeof EvaluacionesNuevaRoute
  IntervencionesIdRoute: typeof IntervencionesIdRoute
  IntervencionesNuevaRoute: typeof IntervencionesNuevaRoute
  TransferenciasIdRoute: typeof TransferenciasIdRoute
  TransferenciasNuevaRoute: typeof TransferenciasNuevaRoute
  AgendasIndexRoute: typeof AgendasIndexRoute
  AuditoriaIndexRoute: typeof AuditoriaIndexRoute
  ConsultaInventariosIndexRoute: typeof ConsultaInventariosIndexRoute
  ConsultaTransferenciasIndexRoute: typeof ConsultaTransferenciasIndexRoute
  EvaluacionesIndexRoute: typeof EvaluacionesIndexRoute
  IntervencionesIndexRoute: typeof IntervencionesIndexRoute
  InventarioIndexRoute: typeof InventarioIndexRoute
  SucursalesIndexRoute: typeof SucursalesIndexRoute
  TransferenciasIndexRoute: typeof TransferenciasIndexRoute
  ApiOrdsSplatRoute: typeof ApiOrdsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendas/': {
      id: '/agendas/'
      path: '/agendas'
      fullPath: '/agendas/'
      preLoaderRoute: typeof AgendasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria/': {
      id: '/auditoria/'
      path: '/auditoria'
      fullPath: '/auditoria/'
      preLoaderRoute: typeof AuditoriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta-inventarios/': {
      id: '/consulta-inventarios/'
      path: '/consulta-inventarios'
      fullPath: '/consulta-inventarios/'
      preLoaderRoute: typeof ConsultaInventariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta-transferencias/': {
      id: '/consulta-transferencias/'
      path: '/consulta-transferencias'
      fullPath: '/consulta-transferencias/'
      preLoaderRoute: typeof ConsultaTransferenciasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluaciones/': {
      id: '/evaluaciones/'
      path: '/evaluaciones'
      fullPath: '/evaluaciones/'
      preLoaderRoute: typeof EvaluacionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluaciones/$id': {
      id: '/evaluaciones/$id'
      path: '/evaluaciones/$id'
      fullPath: '/evaluaciones/$id'
      preLoaderRoute: typeof EvaluacionesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluaciones/nueva': {
      id: '/evaluaciones/nueva'
      path: '/evaluaciones/nueva'
      fullPath: '/evaluaciones/nueva'
      preLoaderRoute: typeof EvaluacionesNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intervenciones/': {
      id: '/intervenciones/'
      path: '/intervenciones'
      fullPath: '/intervenciones/'
      preLoaderRoute: typeof IntervencionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intervenciones/$id': {
      id: '/intervenciones/$id'
      path: '/intervenciones/$id'
      fullPath: '/intervenciones/$id'
      preLoaderRoute: typeof IntervencionesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intervenciones/nueva': {
      id: '/intervenciones/nueva'
      path: '/intervenciones/nueva'
      fullPath: '/intervenciones/nueva'
      preLoaderRoute: typeof IntervencionesNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario/': {
      id: '/inventario/'
      path: '/inventario'
      fullPath: '/inventario/'
      preLoaderRoute: typeof InventarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sucursales/': {
      id: '/sucursales/'
      path: '/sucursales'
      fullPath: '/sucursales/'
      preLoaderRoute: typeof SucursalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferencias/': {
      id: '/transferencias/'
      path: '/transferencias'
      fullPath: '/transferencias/'
      preLoaderRoute: typeof TransferenciasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferencias/$id': {
      id: '/transferencias/$id'
      path: '/transferencias/$id'
      fullPath: '/transferencias/$id'
      preLoaderRoute: typeof TransferenciasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferencias/nueva': {
      id: '/transferencias/nueva'
      path: '/transferencias/nueva'
      fullPath: '/transferencias/nueva'
      preLoaderRoute: typeof TransferenciasNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ords/$': {
      id: '/api/ords/$'
      path: '/api/ords/$'
      fullPath: '/api/ords/$'
      preLoaderRoute: typeof ApiOrdsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  HomeRoute: HomeRoute,
  EvaluacionesIdRoute: EvaluacionesIdRoute,
  EvaluacionesNuevaRoute: EvaluacionesNuevaRoute,
  IntervencionesIdRoute: IntervencionesIdRoute,
  IntervencionesNuevaRoute: IntervencionesNuevaRoute,
  TransferenciasIdRoute: TransferenciasIdRoute,
  TransferenciasNuevaRoute: TransferenciasNuevaRoute,
  AgendasIndexRoute: AgendasIndexRoute,
  AuditoriaIndexRoute: AuditoriaIndexRoute,
  ConsultaInventariosIndexRoute: ConsultaInventariosIndexRoute,
  ConsultaTransferenciasIndexRoute: ConsultaTransferenciasIndexRoute,
  EvaluacionesIndexRoute: EvaluacionesIndexRoute,
  IntervencionesIndexRoute: IntervencionesIndexRoute,
  InventarioIndexRoute: InventarioIndexRoute,
  SucursalesIndexRoute: SucursalesIndexRoute,
  TransferenciasIndexRoute: TransferenciasIndexRoute,
  ApiOrdsSplatRoute: ApiOrdsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
